# Use alpine as base image
FROM alpine

# Custom labels
LABEL mantainer="Jhonattan Millán"
LABEL version="1.0"
LABEL description="A custom Docker image based on Alpine."

# OCI labels
LABEL org.opencontainers.image.authors="Jhonattan Millán"
LABEL org.opencontainers.image.title="Entrypoint Demo"
LABEL org.opencontainers.image.description="A custom Docker image to illustrate the usage of ENTRYPOINT."
LABEL org.opencontainers.image.version="1.0"
LABEL org.opencontainers.image.created="2025-10-04T00:26:00"
LABEL org.opencontainers.image.url=""
LABEL org.opencontainers.image.source=""
LABEL org.opencontainers.image.documentation=""
LABEL org.opencontainers.image.vendor="JHONATTAN M."
LABEL org.opencontainers.image.licenses=""

# Always run this command as entrypoint
ENTRYPOINT ["echo", "ENTRYPOINT EXECUTED"] 
